spring:
  mail:
    host: ${SMTP_HOST:comms-buggregator}
    port: ${SMTP_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

provider:
  simulation:
    failure-rate: ${PROVIDER_FAILURE_RATE:0.2}
    min-delay-ms: 200
    max-delay-ms: 2000
  sms:
    gateway-url: ${SMS_GATEWAY_URL:http://comms-buggregator:8000/sms/twilio}
